package documents

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

var (
	ErrFileTooLarge = errors.New("uploaded file exceeds the configured size limit")
	ErrInvalidPDF   = errors.New("uploaded file is not a PDF")
)

type StoredFile struct {
	StorageKey string
	SHA256     string
	SizeBytes  int64
}

// FileStore owns files beneath Root. Storage keys are generated by this type;
// callers must never supply filesystem paths.
type FileStore struct {
	Root     string
	MaxBytes int64
}

func NewFileStore(root string, maxBytes int64) FileStore {
	return FileStore{Root: root, MaxBytes: maxBytes}
}

func (store FileStore) Save(source io.Reader) (StoredFile, error) {
	if store.MaxBytes <= 0 {
		return StoredFile{}, fmt.Errorf("document size limit must be positive")
	}
	if err := os.MkdirAll(store.Root, 0o750); err != nil {
		return StoredFile{}, fmt.Errorf("create document storage: %w", err)
	}

	temporary, err := os.CreateTemp(store.Root, ".upload-*")
	if err != nil {
		return StoredFile{}, fmt.Errorf("create temporary document: %w", err)
	}
	temporaryPath := temporary.Name()
	cleanupTemporary := true
	defer func() {
		if cleanupTemporary {
			_ = os.Remove(temporaryPath)
		}
	}()

	hash := sha256.New()
	writer := &limitedWriter{
		writer: io.MultiWriter(temporary, hash),
		limit:  store.MaxBytes,
	}

	header := make([]byte, len("%PDF-"))
	if _, err := io.ReadFull(source, header); err != nil {
		_ = temporary.Close()
		return StoredFile{}, ErrInvalidPDF
	}
	if !bytes.Equal(header, []byte("%PDF-")) {
		_ = temporary.Close()
		return StoredFile{}, ErrInvalidPDF
	}

	if _, err := writer.Write(header); err != nil {
		_ = temporary.Close()
		return StoredFile{}, err
	}
	if _, err := io.Copy(writer, source); err != nil {
		_ = temporary.Close()
		if errors.Is(err, ErrFileTooLarge) {
			return StoredFile{}, ErrFileTooLarge
		}
		return StoredFile{}, fmt.Errorf("write document: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return StoredFile{}, fmt.Errorf("close temporary document: %w", err)
	}

	name, err := randomName()
	if err != nil {
		return StoredFile{}, fmt.Errorf("generate storage key: %w", err)
	}
	storageKey := filepath.ToSlash(filepath.Join("documents", name+".pdf"))
	destination, err := store.pathFor(storageKey)
	if err != nil {
		return StoredFile{}, err
	}
	if err := os.MkdirAll(filepath.Dir(destination), 0o750); err != nil {
		return StoredFile{}, fmt.Errorf("create document directory: %w", err)
	}
	if err := os.Rename(temporaryPath, destination); err != nil {
		return StoredFile{}, fmt.Errorf("store document: %w", err)
	}
	cleanupTemporary = false

	return StoredFile{
		StorageKey: storageKey,
		SHA256:     hex.EncodeToString(hash.Sum(nil)),
		SizeBytes:  writer.size,
	}, nil
}

func (store FileStore) Delete(storageKey string) error {
	path, err := store.pathFor(storageKey)
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("delete stored document: %w", err)
	}
	return nil
}

func (store FileStore) pathFor(storageKey string) (string, error) {
	cleanKey := filepath.Clean(filepath.FromSlash(storageKey))
	if cleanKey == "." || filepath.IsAbs(cleanKey) || cleanKey == ".." || strings.HasPrefix(cleanKey, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("invalid document storage key")
	}

	root, err := filepath.Abs(store.Root)
	if err != nil {
		return "", fmt.Errorf("resolve document storage root: %w", err)
	}
	path, err := filepath.Abs(filepath.Join(root, cleanKey))
	if err != nil {
		return "", fmt.Errorf("resolve document storage path: %w", err)
	}
	relative, err := filepath.Rel(root, path)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("document storage key escapes root")
	}
	return path, nil
}

type limitedWriter struct {
	writer io.Writer
	limit  int64
	size   int64
}

func (writer *limitedWriter) Write(data []byte) (int, error) {
	if writer.size+int64(len(data)) > writer.limit {
		remaining := writer.limit - writer.size
		if remaining > 0 {
			written, err := writer.writer.Write(data[:remaining])
			writer.size += int64(written)
			if err != nil {
				return written, err
			}
		}
		return len(data), ErrFileTooLarge
	}

	written, err := writer.writer.Write(data)
	writer.size += int64(written)
	return written, err
}

func randomName() (string, error) {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}
